### ISSUE TITLE
原生属性可以直接.出来

### ISSUE THREAD

**Issue by hkongm** [magnnus/lazyload-observer#1]
https://github.com/magnnus/lazyload-observer/blob/1042f01bee150855e740f8ae6165dd0f9a0f0dc2/src/lazyload.ts#L138

https://github.com/magnnus/lazyload-observer/blob/1042f01bee150855e740f8ae6165dd0f9a0f0dc2/src/lazyload.ts#L155

`img.setAttribute('src', src)` > `img.src = src`

`srcset` 按说也是原生属性，一样的吧

**Comment by magnnus** [comment]
> https://github.com/magnnus/lazyload-observer/blob/1042f01bee150855e740f8ae6165dd0f9a0f0dc2/src/lazyload.ts#L138
> 
> https://github.com/magnnus/lazyload-observer/blob/1042f01bee150855e740f8ae6165dd0f9a0f0dc2/src/lazyload.ts#L155
> 
> `img.setAttribute('src', src)` > `img.src = src`
> 
> `srcset` 按说也是原生属性，一样的吧

造成上面原因是 API 上 get 和 set 对应匹配； 类型注解不是 HTMLImageElement。

**Comment by magnnus** [comment]
v1.0.1 修复了 img 处理函数的元素类型注解
